services:
  app: # Main nextcloud app container
    image: nextcloud:30.0.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./main:/var/www/html:z
      - ./container-config/php-fpm.www.conf:/usr/local/etc/php-fpm.d/www.conf:z
      - /mnt/nextcloud/data:/var/www/html/data:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=4G
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - imaginary

  web: # Nginx container acting as the webserver for the app container
    image: nginx:1.27.2-alpine
    restart: unless-stopped
    ports:
      - 8080:80 # Exposes the nextcloud webserver on port 8080 on the host machine
    volumes:
      - ./main:/var/www/html:z,ro
      - ./container-config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  db: # Database for nextcloud
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env

  redis: # Redis cache for nextcloud
    image: redis:7.4.1-alpine
    restart: unless-stopped

  cron: # Runs cron jobs periodically
    image: nextcloud:30.0.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./main:/var/www/html:z
      - /mnt/nextcloud/data:/var/www/html/data:z
    entrypoint: /cron.sh
    environment:
      - PHP_MEMORY_LIMIT=4G
    env_file:
      - .env

    depends_on:
      - db
      - redis
      - imaginary

  imaginary: # Image preview generator for nextcloud
    image: nextcloud/aio-imaginary:20240925_080419
    restart: unless-stopped
